default:
#	pdflatex mebius.tex
#	pdflatex hopf.tex
	pdflatex mltt.tex
	pdflatex cic.tex
	pdflatex hott.tex
	pdflatex hit.tex
	pdflatex modalities.tex
	pdflatex vol1.tex

clean:
	pdflatex vol1.tex
	rm -f *.bbl
	rm -f *.blg
	rm -f *.toc
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f *.maf
	rm -f *.mtc
	rm -f *.mtc0
