default:
	pdflatex abelian.tex
	pdflatex bart.tex
	pdflatex cat.tex
	pdflatex comprehension.tex
	pdflatex cube.tex
	pdflatex cwf.tex
	pdflatex cwr.tex
	pdflatex fibered.tex
	pdflatex jean.tex
	pdflatex lccc.tex
	pdflatex smc.tex
	pdflatex spt.tex
	pdflatex local.tex
	pdflatex modal.tex
	pdflatex quillen.tex
	pdflatex scheme.tex
	pdflatex simplicial.tex
	pdflatex stable.tex
	pdflatex topos.tex
	pdflatex yoga.tex
	pdflatex vol4.tex

clean:
	pdflatex vol4.tex
	rm -f *.bbl
	rm -f *.blg
	rm -f *.toc
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f *.maf
	rm -f *.mtc
	rm -f *.mtc0
