default:
	pdflatex alonso.tex
	pdflatex felix.tex
	pdflatex joe.tex
	pdflatex robin.tex
	pdflatex yves.tex
	pdflatex vol2.tex

clean:
	rm bloch-eps-converted-to.pdf
	rm pub-eps-converted-to.pdf
	rm sub-eps-converted-to.pdf
	rm sys-eps-converted-to.pdf
	rm -f *.bbl
	rm -f *.blg
	rm -f *.toc
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f *.maf
	rm -f *.mtc
	rm -f *.mtc0
