default:
	pdflatex vol2.tex
	return 0

clean:
	rm bloch-eps-converted-to.pdf
	rm pub-eps-converted-to.pdf
	rm sub-eps-converted-to.pdf
	rm sys-eps-converted-to.pdf
	rm -f *.bbl
	rm -f *.blg
	rm -f *.toc
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f *.maf
	rm -f *.mtc
	rm -f *.mtc0
