default:
	pdflatex anders.tex
	pdflatex frank.tex
	pdflatex henk.tex
	pdflatex laurent.tex
	pdflatex urs.tex
	pdflatex vol3.tex

clean:
	pdflatex vol3.tex
	rm -f *.bbl
	rm -f *.blg
	rm -f *.toc
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f *.maf
	rm -f *.mtc
	rm -f *.mtc0
