default:
	pdflatex vol5.tex

clean:
	rm higher-eps-converted-to.pdf
	rm minimal-eps-converted-to.pdf
	rm pub-eps-converted-to.pdf
	rm sub-eps-converted-to.pdf
	rm sys-eps-converted-to.pdf
	rm -f *.bbl
	rm -f *.blg
	rm -f *.toc
	rm -f *.aux
	rm -f *.log
	rm -f *.out
